### ISSUE TITLE
Set up a code formatter

### ISSUE THREAD

**Issue by albangossard** [ODINN-SciML/ODINN.jl#308]
In order to avoid spending time on how the code should look like, it's a good practice to set up a code formatter.
The code formatter could run locally as a pre-commit hook. Additionally, to be sure that everything that is pushed to the repo was correctly formatted, a test should run in the CI.
We could use [JuliaFormatter](https://github.com/domluna/JuliaFormatter.jl) with a pre-commit hook like [this one](https://github.com/domluna/JuliaFormatter.jl/blob/master/.pre-commit-hooks.yaml) that has to be installed in the repository.
Then, in order to check that the code is properly formatted within the CI, we could use something like:

```yaml
name: Code Format Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format-check:
    name: Check Code Formatting
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1.10' # Adjust Julia version if needed

    - name: Install JuliaFormatter
      run: julia -e 'using Pkg; Pkg.add("JuliaFormatter")'

    - name: Run JuliaFormatter
      run: julia -e 'using JuliaFormatter; format(".");'

    - name: Check for unformatted files
      run: git diff --exit-code
      shell: bash
```
